spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:/testdb
      username: sa
      password:
  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

handlebars:
  suffix: .html
  enabled: true


