spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

handlebars:
  suffix: .html
  enabled: true


